name: Test Build

on:
  workflow_dispatch:

env:
    OUROBOROS_VERSION: test

jobs:
  build:
    name: Docker Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64,arm
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Update Version String
      run: |
        sed -i -r 's/VERSION = "custom"/VERSION = "'$OUROBOROS_VERSION'"/' pyouroboros/__init__.py
        echo $?\
    - name: Build Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: false
        tags: |
          ${{ secrets.DOCKER_USER }}/ouroboros:${{ env.OUROBOROS_VERSION }}
          ${{ secrets.DOCKER_USER }}/ouroboros:latest
